POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "My dfasdf",
    "author": "Josdfe",
    "url": "https://www.gooasdf53gle.com",
    "likes": 44,
    "userId": "66e73e9a42fa68a08fd78aa4"
}

# Response:


###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}