POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "My dfasdf",
    "author": "Josdfe",
    "url": "https://www.gooasdf53gle.com",
    "likes": 44,
    "userId": "66e73e9a42fa68a08fd78aa4"
}


###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "werwer roootototto",
    "name": "werrduuuerper suer",
    "password": "salainen2"
}


### Random user as creator
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "rando title 2",
    "author": "the uknown hero 2",
    "url": "https://www.gosegoose2.com",
    "likes": 332,
    "userId": "rando232323"
}

# Response:
# HTTP/1.1 201 Created
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 167
# ETag: W/"a7-DJNx4Aedr3XvW9AyFeR6C0BDdpE"
# Date: Sun, 15 Sep 2024 21:51:48 GMT
# Connection: close

# {
#   "title": "rando title 2",
#   "author": "the uknown hero 2",
#   "url": "https://www.gosegoose2.com",
#   "likes": 332,
#   "user": "66e73e9a42fa68a08fd78aa4",
#   "id": "66e756f4003cc551ce4a207e"
# }
# and the blogs are:
# [
#   {
#     "title": "My awesome title",
#     "author": "John Doe",
#     "url": "https://www.google.com",
#     "likes": 97,
#     "id": "66e60ac107820d49dad2fd70"
#   },
#   {
#     "title": "My awes45ome title",
#     "author": "Joh345n Doe",
#     "url": "https://www.goo4353gle.com",
#     "likes": 956,
#     "id": "66e60b1107820d49dad2fd73"
#   },
#   {
#     "title": "My dfasdf",
#     "author": "Josdfe",
#     "url": "https://www.gooasdf53gle.com",
#     "likes": 44,
#     "user": {
#       "username": "root",
#       "name": "Superuser",
#       "id": "66e73e9a42fa68a08fd78aa4"
#     },
#     "id": "66e74327571fddb3f70a9264"
#   },
#   {
#     "title": "My dfasdf",
#     "author": "Josdfe",
#     "url": "https://www.gooasdf53gle.com",
#     "likes": 44,
#     "user": {
#       "username": "root",
#       "name": "Superuser",
#       "id": "66e73e9a42fa68a08fd78aa4"
#     },
#     "id": "66e75668003cc551ce4a206c"
#   },
#   {
#     "title": "rando title",
#     "author": "the uknown hero",
#     "url": "https://www.gosegoose.com",
#     "likes": 33,
#     "user": {
#       "username": "root",
#       "name": "Superuser",
#       "id": "66e73e9a42fa68a08fd78aa4"
#     },
#     "id": "66e75681003cc551ce4a2070"
#   },
#   {
#     "title": "rando title 2",
#     "author": "the uknown hero 2",
#     "url": "https://www.gosegoose2.com",
#     "likes": 332,
#     "user": {
#       "username": "root",
#       "name": "Superuser",
#       "id": "66e73e9a42fa68a08fd78aa4"
#     },
#     "id": "66e756f4003cc551ce4a207e"
#   }
# ]
# and the users are:
# [
#   {
#     "username": "root",
#     "name": "Superuser",
#     "blogs": [
#       {
#         "title": "My dfasdf",
#         "url": "https://www.gooasdf53gle.com",
#         "likes": 44,
#         "id": "66e74327571fddb3f70a9264"
#       },
#       {
#         "title": "My dfasdf",
#         "url": "https://www.gooasdf53gle.com",
#         "likes": 44,
#         "id": "66e75668003cc551ce4a206c"
#       },
#       {
#         "title": "rando title",
#         "url": "https://www.gosegoose.com",
#         "likes": 33,
#         "id": "66e75681003cc551ce4a2070"
#       },
#       {
#         "title": "rando title 2",
#         "url": "https://www.gosegoose2.com",
#         "likes": 332,
#         "id": "66e756f4003cc551ce4a207e"
#       }
#     ],
#     "id": "66e73e9a42fa68a08fd78aa4"
#   },
#   {
#     "username": "roootototto",
#     "name": "duuuerper suer",
#     "blogs": [],
#     "id": "66e756bd003cc551ce4a2077"
#   },
#   {
#     "username": "werwer roootototto",
#     "name": "werrduuuerper suer",
#     "blogs": [],
#     "id": "66e756cb003cc551ce4a2079"
#   }
# ]