GET http://localhost:3003/api/blogs HTTP/1.1

# Response:
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 455
# ETag: W/"1c7-DFBkmEPZFweA+OYE0qnujm4Hewo"
# Date: Sun, 15 Sep 2024 21:07:50 GMT
# Connection: close
# 
# [
#   {
#     "title": "My awesome title",
#     "author": "John Doe",
#     "url": "https://www.google.com",
#     "likes": 97,
#     "id": "66e60ac107820d49dad2fd70"
#   },
#   {
#     "title": "My awes45ome title",
#     "author": "Joh345n Doe",
#     "url": "https://www.goo4353gle.com",
#     "likes": 956,
#     "id": "66e60b1107820d49dad2fd73"
#   },
#   {
#     "title": "My dfasdf",
#     "author": "Josdfe",
#     "url": "https://www.gooasdf53gle.com",
#     "likes": 44,
#     "user": {
#       "username": "root",
#       "name": "Superuser",
#       "id": "66e73e9a42fa68a08fd78aa4"
#     },
#     "id": "66e74327571fddb3f70a9264"
#   }
# ]


###
GET http://localhost:3003/api/users HTTP/1.1


# Response:
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 184
# ETag: W/"b8-NZMB9SYVz05imKZ+0+56iL5Q7cM"
# Date: Sun, 15 Sep 2024 21:23:23 GMT
# Connection: close
# 
# [
#   {
#     "username": "root",
#     "name": "Superuser",
#     "blogs": [
#       {
#         "title": "My dfasdf",
#         "url": "https://www.gooasdf53gle.com",
#         "likes": 44,
#         "id": "66e74327571fddb3f70a9264"
#       }
#     ],
#     "id": "66e73e9a42fa68a08fd78aa4"
#   }
# ]